countdown_timer.py

Please add my file in to your repository with label hactoberfest

Countdown_timer

---

simple calculator webapp.html

Added all the basic mathematical operations to the web app

Update simple calculator webapp.html

---

simple calculator webapp.html

powern update to the web application

---

Guess the word.py

Problem Statement – Kochouseph Chittilappilly went to Dhruv Zplanet , a gaming space, with his friends and played a game called “Guess the Word”. Rules of games are –
Computer displays some strings on the screen and the player should pick one string / word if this word matches with the random word that the computer picks then the player is declared as Winner. Kochouseph Chittilappilly’s friends played the game and no one won the game. This is Kochouseph Chittilappilly’s turn to play and he decided to must win the game. What he observed from his friend’s game is that the computer is picking up the string whose length is odd and also that should be maximum. Due to system failure computers sometimes cannot generate odd length words. In such cases you will lose the game anyways and it …

Guess the word.py

---

countdown_timer.py

corrected comment fix
and applied manual time for timer to be entered by user

important updates

---

Fibonacci.java

Can you accept my PR for Hacktoberfest2022? Thank you so much <3!

Added new algorithm: Fibonacci

---

_17FibonacciRecursion.java

I have uploaded a Fibonacci Series program using Recursion. I hope you like it.
please merge/add my file to your repository with the label hacktoberfest. Happy Hacktoberfest-2022 bro 🎉

Fibonacci Series using Recursion

---

Hungry_Snake_Game.py

Please accept my pull request.

Added Hungry_snake_game in python

---

Guessing Game Challenge.py

Added python script for Gussing game

---

program.py

Hacktoberfest

---

clock.py

Added clock program

---

LotteryGame.py

LotteryGame.py

---

emailslicer.py

emailslicer.py

---

Gui_based_caluculator.py

Gui_based_caluculator.py

---

Snakegame.py

Snakegame.py

---

Find duplicates when elements are not limited

Create Find duplicates when elements are not limited

---

Find duplicates in Array in O(N) time

Create Find duplicates in Array in O(N) time

---

Create binary tree in Vertical Order

Create Create binary tree in Vertical Order

---

Traversals Of Binary Tree

Create Traversals Of Binary Tree

---

_24Operators.java

I have uploaded an Operator.java program. I hope you like it. If you like it please accept my pull request. Happy Hacktoberfest-2022 as well as Happy Diwali.

types of Operator

---

bar-chart.js

- [ x] Does this PR fix an existing issue?
- [ o] Have you read the contributing guidelines?
- [ o] Have you made sure that the title is accurate and descriptive of the changes?

created bar chart file for javascript

---

Find Max and Min in Array.c

Create Find Max and Min in Array.c

---

Floyd's Triangle.c
MenuDrivenCalculator.c

Create Floyd's Triangle.c

---

sum_of_n_NaturalNumbers.cpp

sum_of_n_NaturalNumbers.cpp

---

Binary_to_Decimal.cpp

Binary_to_Decimal.cpp

---

Armstrong.py

Modified Armstrong.py

---

MinElement_LinkedList.cpp

MinElement_LinkedList.cpp

---

MaxElement_LinkedList.cpp

MaxElement_LinkedList.cpp

---

Decima_to_Binary.cpp

Decima_to_Binary.cpp

---

test27.c

Contributed

---

mergesort.py

Added merge sort algorithm

---

deletekthnode.cpp

Delete kth node. cpp
